branch-defaults:
  default:
    environment: Addlink-env
environment-defaults:
  Addlink-env:
    branch: null
    repository: null
global:
  application_name: addLink
  default_ec2_keyname: null
  default_platform: PHP 8.0 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
